## Deliverable 3. Create a Travel Itinerary Map.

In [29]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [3]:
# 1a Read the WeatherPy_vacation.csv into a DataFrame.
# Store the CSV you saved created in part one into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation.csv")
vacation_df.head(10)

City_ID           City Country  Max Temp    Lat     Lng  \
0        0           Ruwi      OM     68.00  23.60   58.55   
1        5      Mahebourg      MU     73.40 -20.41   57.70   
2        6          Buala      SB     84.29  -8.14  159.59   
3       12      Oriximina      BR     80.67  -1.77  -55.87   
4       18         Dingle      PH     77.88  11.00  122.67   
5       19         Hasaki      JP     68.00  35.73  140.83   
6       21        Itarema      BR     79.79  -2.92  -39.92   
7       22  San Cristobal      VE     78.80   7.77  -72.22   
8       23        Rikitea      PF     73.72 -23.12 -134.97   
9       24          Arlit      NE     75.31  18.74    7.39   

                           Hotel Name  
0                      Al Falaj Hotel  
1  Shandrani Beachcomber Resort & Spa  
2                Maringe Lagoon Lodge  
3                  Pousada Tia Amélia  
4                         Camp Pasica  
5               Inubosaki Kanko Hotel  
6                         Windvillage  
7                            Pirineos  
8                      Pension Maro'i  
9                Hôtel Telwa Bungalow

In [5]:
# 1b Store the CSV you saved created in part one into a DataFrame.
clean_hotel_df = pd.read_csv("WeatherPy_Database.csv")
clean_hotel_df.head(10)

City_ID            City Country    Lat     Lng  Max Temp  Humidity  \
0        0            Ruwi      OM  23.60   58.55     68.00        72   
1        1      Naryan-Mar      RU  67.67   53.09     14.59        96   
2        2      Bredasdorp      ZA -34.53   20.04     60.80        87   
3        3          Castro      BR -24.79  -50.01     61.16        97   
4        4          Albany      US  42.60  -73.97     41.00        69   
5        5       Mahebourg      MU -20.41   57.70     73.40        78   
6        6           Buala      SB  -8.14  159.59     84.29        73   
7        7  Vestmannaeyjar      IS  63.44  -20.27     44.17        73   
8        8       Grindavik      IS  63.84  -22.43     41.00        86   
9        9       Kununurra      AU -15.77  128.73     91.40        52   

   Cloudiness  Wind Speed  
0           0        3.36  
1           0        8.57  
2         100       10.29  
3           2        6.15  
4           2        2.08  
5          75       16.11  
6          76        1.63  
7           0        2.35  
8           0       10.29  
9         100        6.93

In [6]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [8]:
# 4a. Add a marker layer for each city to the map.
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start_df = vacation_df.loc[vacation_df["City"] == "Laguna"]
vacation_end_df = vacation_df.loc[vacation_df["City"] == "Laguna"]
vacation_stop1_df = vacation_df.loc[vacation_df["City"] == "Kapaa"]
vacation_stop2_df = vacation_df.loc[vacation_df["City"] == "Waipawa"] 
vacation_stop3_df = vacation_df.loc[vacation_df["City"] == "Innisfail"] 

In [34]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start_df.to_numpy()
start

array([[154, 'Laguna', 'US', 68.0, 38.42, -121.42,
        'Holiday Inn Express & Suites Elk Grove Central - Hwy 99']],
      dtype=object)

In [21]:
end = vacation_end_df.to_numpy()
end

array([[154, 'Laguna', 'US', 68.0, 38.42, -121.42,
        'Holiday Inn Express & Suites Elk Grove Central - Hwy 99']],
      dtype=object)

In [22]:
stop1 = vacation_stop1_df.to_numpy()
stop1

array([[52, 'Kapaa', 'US', 82.4, 22.08, -159.32,
        'Sheraton Kauai Resort at Coconut Beach']], dtype=object)

In [32]:
stop2 = vacation_stop2_df.to_numpy()
stop2

array([[222, 'Waipawa', 'NZ', 66.2, -41.41, 175.52, 'Tora Coastal Walk']],
      dtype=object)

In [24]:
stop3 = vacation_stop3_df.to_numpy()
stop3

array([[143, 'Innisfail', 'AU', 83.3, -17.53, 146.03, 'Moondarra Motel']],
      dtype=object)

In [7]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".



In [ ]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "mode": "walking"
    "key": g_key}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["origin"] = f"{lat},{lng}"
    params["destination"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/directions/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
   
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try: hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError): print("Hotel not found... skipping.")
    
start_df.head(10)

In [ ]:
# Set parameters for start to stop 1
params["origin"] = 38.42, -121.42
params["destination"] = 22.08, -159.32
params{"mode": "walking"
        "key": g_key}
    
# Set up the base URL for the Google Directions API to get JSON data.
base_url = "https://maps.googleapis.com/maps/api/directions/json"

# Make request and retrieve the JSON data from the search. 
leg1 = requests.get(base_url, params=params).json()
        
leg1_df.head(10)

In [8]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([],ignore_index=True)
itinerary_df

In [9]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [10]:
# 11a. Add a marker layer for each city to the map. 
name = itinerary_df["City"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

In [ ]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

In [ ]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

In [ ]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig